# Generated by Django 4.1.5 on 2023-04-30 01:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_external_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='buyoperation',
            name='operation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Operacion'),
        ),
        migrations.AddField(
            model_name='extractoperation',
            name='operation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Operacion'),
        ),
        migrations.AddField(
            model_name='selloperation',
            name='operation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Operacion'),
        ),
        migrations.AddField(
            model_name='transferoperation',
            name='operation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Operacion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='external_code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
