# Generated by Django 4.1.5 on 2023-04-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_product_box_size_alter_account_kind"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transferoperation",
            name="transfer_date",
        ),
        migrations.AddField(
            model_name="product",
            name="last_price_date",
            field=models.DateField(
                null=True, verbose_name="Ultima actualizacion precio"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="last_price_date",
            field=models.DateField(
                null=True, verbose_name="Ultima actualizacion precio"
            ),
        ),
    ]
