# Generated by Django 4.1.5 on 2023-05-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_transferoperation_transfer_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferoperation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
