# Generated by Django 4.1.5 on 2023-06-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_transferoperation_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="internal",
            field=models.BooleanField(default=True),
        ),
    ]
