# Generated by Django 4.1.5 on 2023-06-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_account_internal"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractoperation",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
