# Generated by Django 4.1.5 on 2023-06-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_extractoperation_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={},
        ),
        migrations.RemoveField(
            model_name="service",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="service",
            name="enabled",
        ),
        migrations.RemoveField(
            model_name="service",
            name="last_price_date",
        ),
        migrations.RemoveField(
            model_name="service",
            name="price",
        ),
        migrations.AlterField(
            model_name="extractoperation",
            name="amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
