# Generated by Django 4.1.5 on 2023-07-18 00:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_service_options_remove_service_cost_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="internal",
            new_name="is_business",
        ),
    ]
