# Generated by Django 4.1.5 on 2023-07-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_rename_internal_account_is_business"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractoperation",
            name="cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="extractoperation",
            name="observations",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="extractoperation",
            name="profit",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
            preserve_default=False,
        ),
    ]
