# Generated by Django 4.1.5 on 2023-07-20 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_extractoperation_cost_extractoperation_observations_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("transport", "Transporte"), ("other", "Otros")],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ItemIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("qty", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="buyoperation",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="buyoperation",
            name="observations",
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name="BuyItem",
        ),
        migrations.AddField(
            model_name="itemincome",
            name="operation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itemincome",
                to="core.buyoperation",
            ),
        ),
        migrations.AddField(
            model_name="itemincome",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.product"
            ),
        ),
        migrations.AddField(
            model_name="expenseoperation",
            name="operation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.buyoperation"
            ),
        ),
    ]
