# Generated by Django 4.1.5 on 2023-08-27 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_expenseoperation_itemincome_buyoperation_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="selloperation",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="selloperation",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="selloperation",
            name="profit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="buyoperation",
            name="source_accounts",
            field=models.ManyToManyField(
                related_name="%(app_label)s_%(class)s_source_account", to="core.account"
            ),
        ),
        migrations.AlterField(
            model_name="extractoperation",
            name="source_accounts",
            field=models.ManyToManyField(
                related_name="%(app_label)s_%(class)s_source_account", to="core.account"
            ),
        ),
        migrations.AlterField(
            model_name="itemincome",
            name="operation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.buyoperation"
            ),
        ),
        migrations.AlterField(
            model_name="selloperation",
            name="source_accounts",
            field=models.ManyToManyField(
                related_name="%(app_label)s_%(class)s_source_account", to="core.account"
            ),
        ),
        migrations.AlterField(
            model_name="transferoperation",
            name="source_accounts",
            field=models.ManyToManyField(
                related_name="%(app_label)s_%(class)s_source_account", to="core.account"
            ),
        ),
    ]
